--IS_NULL 1)
SELECT ANIMAL_ID FROM ANIMAL_INS
WHERE ISNULL(NAME)

--IS_NULL 2)
SELECT ANIMAL_ID FROM ANIMAL_INS
WHERE NOT ISNULL(NAME)

--IS_NULL 3)
SELECT ANIMAL_TYPE, IFNULL(NAME,"No name") "NAME", SEX_UPON_INTAKE FROM ANIMAL_INS
ORDER BY ANIMAL_ID
